export const CAREERS = [
  {
    position: 'Frontend Developer',
    company: 'Harian Kompas',
    logo: '/careers/kompas.jpeg',
    location: 'Jakarta',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2023-04',
    end_date: null,
    link: 'https://www.kompas.id',
  },
  {
    position: 'Frontend Developer',
    company: 'AlteaCare',
    logo: '/careers/alteacare.png',
    location: 'Tangerang Selatan',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2022-08',
    end_date: '2023-04',
    link: 'https://alteacare.com',
  },
  {
    position: 'Fullstack Developer',
    company: 'importir.org',
    logo: '/careers/importir.jpeg',
    location: 'Tangerang',
    location_type: 'On Site',
    type: 'Fulltime',
    start_date: '2022-02',
    end_date: '2022-08',
    link: 'https://importir.org',
  },
  {
    position: 'IT Management Trainee',
    company: 'importir.org',
    logo: '/careers/importir.jpeg',
    location: 'Tangerang',
    location_type: 'On Site',
    type: 'Fulltime',
    start_date: '2022-04',
    end_date: '2022-08',
    link: 'https://importir.org',
  },
];
